### ISSUE TITLE
First press of arrow keys after foregrounding doesn’t do anything

### ISSUE THREAD

**Issue by abreen** [visit1985/mdp#84] opened 2015-03-29 19:51 UTC
After foregrounding with `fg`, a left or right keypress doesn’t advance the slideshow until I press it again. Spacebar always works, however.

OS X 10.10.3
iTerm 2.0.0.20141103 (terminal emulator)
fish 2.1.2 (shell)
compiled with clang 600.0.57

**Comment by visit1985** [comment] 2015-03-31 20:21
Can't reproduce this on Arch Linux and I don't own a Mac.
Can you help me debugging it?

I assume the first key-press sends some control sequence which can not be processed.

You'd need to add the following two lines in viewer.c after line 337 (`c = getch();`) and compile `mdp` from source:

    fwprintf(stderr, L"char: %i\n", c);
    usleep(1000000);

If you run this patched version, it should display a message (`char: NNN`) for a second after each key-press.

Would be interesting to see, which number is printed on first and second left/right key-press after foregrounding.

**Comment by abreen** [comment] 2015-03-31 20:47
Here’s a transcript of what I get: https://asciinema.org/a/18246

It looks like `ESC` `[` `C` gets sent, which is a CSI sequence. The `C` represents the escape code for “cursor forward.” I know what escape codes are, but I don’t know why one would be sent to `mdp`.

I also tried this in OS X Terminal, with the same result.

**Comment by visit1985** [comment] 2015-03-31 21:34
[Interesting](http://stackoverflow.com/questions/1182665/curses-getting-arrow-keys).

Normally [this](https://github.com/visit1985/mdp/blob/master/src/viewer.c#L172) should avoid it according to the [docs](http://invisible-island.net/ncurses/man/curs_inopts.3x.html). 
Maybe we need to set `keypad(content, TRUE);` after the definition of the [content window](https://github.com/visit1985/mdp/blob/master/src/viewer.c#L238) and use `wgetch(content)`instead of `getch()`.

Can you test this?

**Comment by visit1985** [comment] 2015-07-15 21:42
As it is a minor issue, and definitely related to ncurses on OS-X only, I'll close this for now.

**Closed by visit1985** 2015-07-15 21:42 UTC
Labels: help wanted
